# Generated by Django 3.2.8 on 2024-01-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactmedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=20, null=True)),
                ('message', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
